import argparse
from pathlib import Path

import torch

from training.data import CLASSES, MEAN, STD
from training.train import build_model


def export_onnx(checkpoint: Path, out_path: Path, opset: int = 18) -> None:
    ckpt = torch.load(checkpoint, map_location="cpu")
    model = build_model(ckpt["arch"], len(ckpt["class_names"]))
    model.load_state_dict(ckpt["state_dict"])
    model.eval()
    dummy = torch.rand(1, 3, 224, 224)
    torch.onnx.export(
        model,
        dummy,
        str(out_path),
        input_names=["input"],
        output_names=["output"],
        opset_version=opset,
    )


def write_contract(out_path: Path, label_names: list[str]) -> None:
    mean = ", ".join(str(x) for x in MEAN)
    std = ", ".join(str(x) for x in STD)
    out_path.write_text(
        f"""# ONNX Model Contract

This file is generated by `inference/export.py`. The app MUST match these
values exactly; the parity test in `app/src/ml/__tests__/preprocess.test.ts`
enforces it.

## Input

- Tensor name: `input`
- Shape: `[1, 3, 224, 224]` (batch 1, CHW)
- Dtype: float32
- Values: RGB pixels resized to 224x224 (bicubic), then normalized:
  `(pixel / 255 - mean) / std` per channel.

## Normalization stats

- mean: [{mean}]
- std: [{std}]

## Output

- Tensor name: `output`
- Shape: `[1, {len(label_names)}]`, logits (pre-softmax)
- Class index order: {label_names}

## Runtime

- ONNX opset 18, fp32, int8 dynamic quantization for the shipped model.
- No float16 tensors anywhere (Hermes/RN 0.86 has no Float16Array).
"""
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--contract", type=Path, default=Path("docs/onnx-contract.md"))
    args = parser.parse_args()
    export_onnx(args.checkpoint, args.out)
    write_contract(args.contract, CLASSES)
    print(f"exported {args.out}")


if __name__ == "__main__":
    main()
